/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package DSA.JAVA;

import org.junit.Test;

import static org.junit.Assert.assertArrayEquals;

public class ArrayShiftTest {
    @Test public void arrayShiftTestOdd() {
        ArrayShift classUnderTest = new ArrayShift();
        assertArrayEquals(new int[] {2,3,4,5,6}, classUnderTest.insertShiftArray(new int[]{2,3,5,6},4));
    }
    @Test public void arrayShiftTestEven() {
        ArrayShift classUnderTest = new ArrayShift();
        assertArrayEquals(new int[] {2,3,4,5,6,7}, classUnderTest.insertShiftArray(new int[]{2,3,4,6,7},5));
    }
    @Test public void arrayShiftTestEmpty() {
        ArrayShift classUnderTest = new ArrayShift();
        assertArrayEquals(new int[] {42}, classUnderTest.insertShiftArray(new int[]{},42));
    }
}
